# Generated by Django 4.2.4 on 2023-08-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("none", "반복 없음"),
                            ("weekly", "매주 반복"),
                            ("monthly", "매달 반복"),
                            ("yearly", "매년 반복"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("title", models.CharField(max_length=25)),
                ("description", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("doing", "Doing"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
