# Generated by Django 4.2.2 on 2023-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat',
            field=models.CharField(choices=[('none', '반복 없음'), ('weekly', '매주 반복'), ('monthly', '매달 반복'), ('yearly', '매년 반복')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
