# Generated by Django 4.2.2 on 2023-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
                ('members', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=15)),
            ],
        ),
    ]
